<?php
    echo '<div id="navlogo">';
      echo '<a href="mailto:jkltech@gmail.com"><img src="images/icons8-team-goal-96.png" style="width:auto; height:50px;" alt="20-I Tech Logo"></a>';
    echo '</div>';
    echo '<input type="checkbox" id="navbutton">';
    echo '<div id="navicon">';
      echo '<label for="navbutton">&#x2630;</label>';
    echo '</div>';
    echo '<div id="navlinks">';
      echo '<a class="menu" href="index.php">Home</a>';
      echo '<a class="menu" href="about.php">About</a>';
      echo '<a class="menu" href="jobs.php">Jobs</a>';
      echo '<a class="menu" href="apply.php">Apply</a>';
      //echo '<a class="menu" href="enhancements.php">Enhancements</a>';
      echo '<a class="menu" href="login.php">Login</a>';
    echo '</div>';
?>